new branch
dawidmiechowski/liquid pull request #2
Opened 2022-03-24 11:55 UTC by dawidmiechowski

2022-03-24 12:04 UTC, Sato2023 commented
hei

2022-03-30 10:52 UTC, godot requested changes

2022-03-30 10:52 UTC, godot commented on project1/app/views/pages/selectt.html.liquid
> -            document.getElementById("toggleVisibilityButton").addEventListener("click", function(button) {
please move all JS code into a separate file 
`app/assets/scripts/app.js`

2022-03-30 10:55 UTC, godot commented
also please change a directory structure of the project
- delete nesting in a `project1` folder - meaning move everything from this folder up

2022-04-02 12:27 UTC, godot approved these changes
OK merge

2022-04-02 16:08 UTC, merged